package:
  name: mkdocs-rtd-dropdown
  version: "0.0.11"

source:
  git_url: https://github.com/gabm/mkdocs-rtd-dropdown.git
  git_rev: 2f5598fd4bd2c2f2d7ee06069aeb0f26ed734c48


build:
  noarch: python
  number: 1
  detect_binary_files_with_prefix: true
  script:
    - python setup.py install

requirements:
  build:
    - python
    
  run:
    - python
    - mkdocs
