stages:
  - build
  - test
  - deploy


.build-linux: &build-linux
  stage: build
  tags:
    - linux
  script:
    - conda install -y conda-build
    - conda-build recipe --croot $(pwd)/builds --no-test
  artifacts:
    paths:
      - builds/noarch/*.tar.bz2
      - builds/linux-64/*.tar.bz2
      - builds/linux-aarch64/*.tar.bz2

.test-linux: &test-linux
  stage: test
  tags:
    - linux
  script:
    - conda install -y conda-build
    - conda-build recipe --croot $(pwd)/builds -t

build-linux-intel64:
  <<: *build-linux
  image: draive-ci-intel64:latest

test-linux-intel64:
  <<: *test-linux
  image: draive-ci-intel64:latest

test-win-intel64:
  stage: test
  tags:
    - win
  script:
    - conda install -y conda-build
    - conda-build recipe --croot $(Join-Path (pwd) builds) -t

deploy-to-dev:
  image: draive-ci-intel64:latest
  stage: deploy
  environment: link.developers
  tags:
    - linux
  script:
    - conda install darts-cli -y
    - darts-cli conda link.developers $(pwd)/builds/
  only:
    - master@link.developers/native-libs/mkdocs-rtd-dropdown
